# Generated by Django 3.1.2 on 2020-10-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
