# Generated by Django 3.1.2 on 2020-10-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplist', '0002_auto_20201008_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmodel',
            name='category',
            field=models.CharField(choices=[('health', '健康'), ('life', '生活'), ('sdgs', '関西SDGs')], max_length=50),
        ),
    ]
